# This is a basic workflow to help you get started with Actions

name: update_issues

# Controls when the action will run. 
on:
  schedule:
    - cron: "* * * * *" #runs cronjob every minute
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:
  update: #name of job
    runs-on: ubuntu-latest #determines os for running action
    steps:
      - uses: actions/checkout@v2.1.0 #sets environment for github action
      - run:
          python -m pip install --upgrade pip #sets package installing up
      - run:
          pip install PyGithub google-api-python-client google-auth-httplib2 google-auth-oauthlib #get access to github and google api
      - run:
          python feedback/update_issues.py #this is the python script for updating the feedback and auto-converting them to github issues
        env: 
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS}}
          git_token: ${{secrets.GH_TOKEN}} #fetches the github api access token from the secrets of the repo
